### ISSUE TITLE
partial_direct_Obs not defined

### ISSUE THREAD

**Issue by Balinus** [nansencenter/DA-tutorials#1]
Hello!

Thanks for the tutorial!

In T4, there is a missing function.

```python
# Observe 0th component only
Obs = partial_direct_Obs(M,[0])

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-f3df1c2a2da5> in <module>
      7 
      8 # Observe 0th component only
----> 9 Obs = partial_direct_Obs(M,[0])
     10 Obs['noise'] = 1000
     11 

NameError: name 'partial_direct_Obs' is not defined
```

**Comment by patnr** [comment]
Hi

I renamed it to `partial_Id_Obs` in the latest master commit for DAPPER.

Note: the DA-tutorials require (at the moment) DAPPER v. 0.9.6, which you ought to get if you follow the install instructions. Verify with:
```
import dapper
dapper.__version__
```

**Comment by Balinus** [comment]
Thanks! I was on master. :)

**Comment by paccarfx** [comment]
> Hi
> 
> I renamed it to `partial_Id_Obs` in the latest master commit for DAPPER.
> 
> Note: the DA-tutorials require (at the moment) DAPPER v. 0.9.6, which you ought to get if you follow the install instructions. Verify with:
> 
> ```
> import dapper
> dapper.__version__
> ```

 It worked.
Many Thanks.
