### ISSUE TITLE
print_averages method in T9

### ISSUE THREAD

**Issue by sophie-mauran** [nansencenter/DA-tutorials#3]
Hello,

I've run into an error when executing the last tutorial and wanting to call print_averages method : the exact error is

'ValueError: dictionary update sequence element #0 has length 9; 2 is required'.

Thank you in advance for helping me,

Sophie

**Comment by patnr** [comment]
Many thanks for the notice. This has been fixed by replacing the chapter with the first example script of DAPPER.

https://github.com/nansencenter/DAPPER/tree/master/examples
