### ISSUE TITLE
'Show' cells not working

### ISSUE THREAD

**Issue by HarryLuyt** [nansencenter/DA-tutorials#4]
Good day, Patrick!

First off, thank you for the tutorials and for making them freely available!

When doing the tutorials on Colab I found that running the #show_answer and #show_example cells did not produce any output. But the cells ran successfully, shown by the green tick. I am not sure if I must do something more for the answer or example to show, but my limited Jupyter notebook experience tells me it should just show.

I am using Google Chrome on Linux and the same behaviour persisted when using Firefox and when using binder. I have not looked to see if this also persists beyond the first two tutorials.

**Comment by patnr** [comment]
Hi! I'm guessing you just need to remove the leading `#` (Python comment indicator), which is there to prevent revealing the answer by default.

**Comment by HarryLuyt** [comment]
But of course!

I thought it was some kind of special syntax for some reason. Thanks for clearing that up!

Just tested and it works as expected when uncommenting the command :+1:
