### ISSUE TITLE
EnKF for 2D Grid data

### ISSUE THREAD

**Issue by shahbazbaig** [nansencenter/DA-tutorials#5]
Hi author,
I have found these tutorial exercise good to for making understanding of EnKF and its background. In your tutorials and other references, I mostly found EnKF for multivariates but I have not found any example or guidance to perform assimilation for 2-dim grid based data e.g., weather data from satellites and weather forecast models where matric based computation is required.  Do you think your example code is also application for this kind of DA? If not, can you guide me what should I consider to achieve this? Or EnKF is only applicable for vector based data manipulation?

**Comment by patnr** [comment]
The code herein will take you pretty far but not quite to real-world DA cases. I suggest you have a look at one of [these alternatives](https://github.com/nansencenter/DAPPER#similar-projects)
